
run:
  timeout: 10m
  tests: true
  # default is true. Enables skipping of directories:
  #   vendor$, third_party$, testdata$, examples$, Godeps$, builtin$
  skip-dirs-use-default: true
  #  skip-files:
  skip-dirs:
    - contract #from test contract
linters:
  disable-all: true
  enable:
    - deadcode
    - goconst
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unconvert
    - unused
    - varcheck
    - gosec
    - typecheck
    - gofmt
    - dupl
#    - gocyclo
#    - funlen
#    - lll
#    - nestif

linters-settings:
  gofmt:
    simplify: true
  goconst:
    min-len: 2 # minimum length of string constant
    min-occurrences: 6 # minimum number of occurrences
  gosimple:
    # Select the Go version to target. The default is '1.13'.
    go: "1.15"
  lll:
    # max line length, lines longer will be reported. Default is 120.
    # '\t' is counted as 1 character by default, and can be changed with the tab-width option
    line-length: 120
    # tab width in spaces. Default to 1.
    tab-width: 1
  funlen:
    lines: 60
    statements: 40
  dupl:
    # tokens count to trigger issue, 150 by default
    threshold: 120
issues:
  exclude-rules:
    - path: .*_test.go
      linters:
        - unused
        - deadcode
        - ineffassign
        - staticcheck
        - forbidigo
        - dupl
