chain_client:
  # 链ID
  chain_id: "chain01"
  # 组织ID
  org_id: "wx-org1.chainmaker.org"
  # 客户端用户私钥路径，使用绝对路径
  user_key_file_path: "/home/chainv2.3/chainmaker-cross/config/chainmaker/crypto-config/wx-org1.chainmaker.org/user/client1/client1.tls.key"
  # 客户端用户证书路径，使用绝对路径
  user_crt_file_path: "/home/chainv2.3/chainmaker-cross/config/chainmaker/crypto-config/wx-org1.chainmaker.org/user/client1/client1.tls.crt"
  # 客户端用户交易签名私钥路径(若未设置，将使用user_key_file_path)，使用绝对路径
  user_sign_key_file_path: "/home/chainv2.3/chainmaker-cross/config/chainmaker/crypto-config/wx-org1.chainmaker.org/user/client1/client1.tls.key"
  # 客户端用户交易签名证书路径(若未设置，将使用user_crt_file_path)，使用绝对路径
  user_sign_crt_file_path: "/home/chainv2.3/chainmaker-cross/config/chainmaker/crypto-config/wx-org1.chainmaker.org/user/client1/client1.tls.crt"
  nodes:
    - # 节点地址，格式为：IP:端口:连接数
      node_addr: "192.168.30.128:12301"
      # 节点连接数
      conn_cnt: 5
      # RPC连接是否启用双向TLS认证
      enable_tls: true
      # 信任证书池路径，使用绝对路径
      trust_root_paths:
        - "/home/chainv2.3/chainmaker-cross/config/chainmaker/crypto-config/wx-org1.chainmaker.org/ca"
        - "/home/chainv2.3/chainmaker-cross/config/chainmaker/crypto-config/wx-org2.chainmaker.org/ca"
      # TLS hostname
      tls_host_name: "chainmaker.org"
    - # 节点地址，格式为：IP:端口:连接数
      node_addr: "192.168.30.128:12302"
      # 节点连接数
      conn_cnt: 5
      # RPC连接是否启用双向TLS认证
      enable_tls: true
      # 信任证书池路径，使用绝对路径
      trust_root_paths:
        - "/home/chainv2.3/chainmaker-cross/config/chainmaker/crypto-config/wx-org1.chainmaker.org/ca"
        - "/home/chainv2.3/chainmaker-cross/config/chainmaker/crypto-config/wx-org2.chainmaker.org/ca"
      # TLS hostname
      tls_host_name: "chainmaker.org"